[pytest]
pythonpath = .
testpaths = backend/tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore:Trying to unpickle estimator.*:sklearn.exceptions.InconsistentVersionWarning
